// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }


  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyObg0okwSIGdKQpHyzWHqk8xSBlwLK7w',  // API Key
    appId: '1:655632443224:android:9875b6ad94e9345f60e72d',  // App ID
    messagingSenderId: '655632443224',  // Messaging Sender ID (project_number)
    projectId: 'ebazar-ef30c',  // Project ID
    storageBucket: 'ebazar-ef30c.firebasestorage.app',  // Storage Bucket
  );

/*
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmUQcHSujt5ZZC0_ME7stWuMXx1FZR5is',  // API Key from your Firebase configuration
    appId: '1:36985304599:android:1f681bceb3fcd589d44e52',  // Android App ID from the JSON
    messagingSenderId: '6343732161',  // Messaging Sender ID
    projectId: 'Ebozor-bee45',  // Project ID
    storageBucket: 'Ebozor-bee45.firebasestorage.app',  // Storage Bucket
  );



  // static const FirebaseOptions android = FirebaseOptions(
  //   apiKey: 'AIzaSyApCJcVfUTKAdfiNB2vZ399YgJEFy_d-vk',
  //   appId: '1:6343732161:android:be9cbc67ef8a19792b5d40',
  //   messagingSenderId: '6343732161',
  //   projectId: 'eclassify-wrteam',
  //   storageBucket: 'Ebozor-bee45.firebasestorage.app',
  // );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmUQcHSujt5ZZC0_ME7stWuMXx1FZR5is',
    appId: '1:6343732161:ios:5cc58a2dcfbbb66b2b5d40',  // You can also use the value from the Dart config
    messagingSenderId: '6343732161',  // You may want to keep this consistent with the iOS project
    projectId: 'Ebozor-bee45',
    storageBucket: 'Ebozor-bee45.firebasestorage.app',
    androidClientId: '36985304599-o5u3fcsu1ubfdb01qfbu3vntnvcjd07r.apps.googleusercontent.com',  // Same as in your config
    iosClientId: '36985304599-gh3h4ropppmlirddla2tssa9ofpcnq86.apps.googleusercontent.com',
    iosBundleId: 'com.cashgatetech.Ebozor',  // Updated Bundle ID from JSON
  );
  */


  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyObg0okwSIGdKQpHyzWHqk8xSBlwLK7w',  // API Key
    appId: '1:655632443224:ios:9875b6ad94e9345f60e72d',  // App ID for iOS
    messagingSenderId: '655632443224',  // Messaging Sender ID (project_number)
    projectId: 'ebazar-ef30c',  // Project ID
    storageBucket: 'ebazar-ef30c.firebasestorage.app',  // Storage Bucket
    iosClientId: '655632443224-962i5tpnps5l782th633actn19rb0p9e.apps.googleusercontent.com',  // iOS Client ID
    iosBundleId: 'com.app.ebazar',  // iOS Bundle ID
  );

}
